databases:
  - name: postgres
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: Joker
    env: docker
    region: frankfurt
    repo: https://github.com/jepthoniq/lMl10l      
    branch: Scalingo
    envVars:
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: ENV 
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_USERNAME
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: TZ
        sync: false 
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString   
    autoDeploy: false
