databases:
  - name: postgres
    ipAllowList: []
    plan: free
services:
  - type: web
    plan: free
    name: Joker
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: gunicorn app:app & bash start
    repo: https://github.com/jepthoniq/lMl10l      
    branch: Scalingo
    envVars:
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: ENV 
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TG_BOT_USERNAME
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: TZ
        sync: false 
        fromDatabase:
          name: postgres
          property: connectionString   
    autoDeploy: false
